project_name: auriga
before:
  hooks:
    - go mod tidy
builds:
  - main: ./app/cmd
    binary: auriga
    env:
    - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - docs/*
      - README.md
      - README_jp.md
      - .env.sample
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  prerelease: auto
