name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"
      - uses: actions/setup-go@v4
        with:
          go-version: "1.17"
      - name: Install Serverless CLI
        run: sudo npm i -g serverless@3.15.2
      - name: Install Serverless Offline
        run: sudo npm i -g serverless-offline@9.0.0
      - name: Install Serverless utils
        run: sudo npm i -g @serverless/utils@6.7.0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::903624094458:role/auriga_deploy'
      - name: Serverless deploy
        run: make deploy
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
          SLACK_SIGNING_SECRET: ${{secrets.SLACK_SIGNING_SECRET}}
