name: deploy

on:
  push:
#    branches:
#      - 'main'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: ichikimfw/node-go:14.17.0-1.17.7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Serverless CLI
        run: sudo npm i -g serverless@3.22.0
      - name: Install Serverless Offline
        run: sudo npm i -g serverless-offline@9.0.0
      - name: Install Serverless utils
        run: sudo npm i -g @serverless/utils@6.7.0
      - name: Install simple-git # https://github.com/serverless/serverless/issues/12418#issuecomment-2048920297
        run: |
          CURRENT_DIR=$(pwd)
          echo "CURRENT_DIR=$CURRENT_DIR" >> $GITHUB_ENV
          cd /usr/local/lib/node_modules/serverless
          sudo npm i simple-git@3.22.0
      - name: Serverless deploy
        run: |
          cd $CURRENT_DIR
          make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
          SLACK_SIGNING_SECRET: ${{secrets.SLACK_SIGNING_SECRET}}
